# vim: sts=2 ts=2 sw=2 et ai
#
# SET ALL PARAMS IN CONFIG SECTION USING UNDERSCORE, NOT HYPHEN
# so that it works correctly
{% load_yaml as default_config %}
Debian:
  fanout: 64
  connect_timeout: 15
  command_timeout: 0
  color: auto
  fd_max: 16384
  history_size: 100
  node_count: 'yes'
  verbosity: 1
{% endload %}
